version: '3.9'
services:
  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:7.13.2
    environment:
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
      - 9300:9300
    stdin_open: true
    tty: true
    network_mode: bridge
    
  kibana:
    container_name: kibana
    image: kibana:7.13.2
    ports:
      - 5601:5601
    links:
      - elasticsearch:elasticsearch
    depends_on:
      - elasticsearch
    stdin_open: true
    tty: true
    network_mode: bridge
    
  logstash:
    container_name: logstash
    image: logstash:7.13.2
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf    #logstash conf file
      - ./logstash.template.json:/usr/share/logstash/templates/logstash.template.json
    ports:
      - 5044:5044
    links:
      - elasticsearch:elasticsearch
    depends_on:
      - elasticsearch
    stdin_open: true
    tty: true
    network_mode: bridge
    
  filebeat:
    user: root
    container_name: filebeat
    image: docker.elastic.co/beats/filebeat:7.13.2
    links:
      - logstash:logstash
    depends_on:
      - logstash
    volumes:
      - /var/run/docker.sock:/host_docker/docker.sock
      - /var/lib/docker:/host_docker/var/lib/docker
      - ../../../var/log/remote_log:/usr/share/filebeat/remote_log  #use your log file location to update this line
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml
    command: ["--strict.perms=false"]
    stdin_open: true
    tty: true
    network_mode: bridge
    deploy:
      mode: global